title: "Fisayo | Data Analyst Portfolio"

description: "Data Analyst skilled in SQL, Power BI, and Excel, transforming data into actionable business insights."

logo: "oluwafisayomi.jpeg"

show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
